create table modules (
  id bigint generated by default as identity primary key,
  day_number int not null unique,
  title text not null,
  description text
);

create table sections (
  id bigint generated by default as identity primary key,
  module_id bigint not null references modules(id),
  type text not null,
  title text not null,
  "order" int not null,
  duration int,
  description text
);

create table vocabulary (
  id bigint generated by default as identity primary key,
  section_id bigint not null references sections(id),
  term text not null,
  translation text,
  audio_url text
);

create table dialogues (
  id bigint generated by default as identity primary key,
  section_id bigint not null references sections(id),
  title text,
  lines jsonb,
  audio_url text
);

create table exercises (
  id bigint generated by default as identity primary key,
  section_id bigint not null references sections(id),
  question text not null,
  type text,
  options jsonb,
  correct_answer text,
  explanation text
);

create table practice_prompts (
  id bigint generated by default as identity primary key,
  section_id bigint not null references sections(id),
  scenario text,
  officer_prompt text,
  expected_response text,
  tip text,
  audio_url text
);

create table quizzes (
  id bigint generated by default as identity primary key,
  module_id bigint not null references modules(id),
  question text not null,
  type text,
  options jsonb,
  correct_answer text,
  explanation text
); 